adding simulating error

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,5 +11,8 @@ jobs:
 
       - name: Run a sample GitHub action
         run: echo "this workflow runs successfully for this particular action"
+
+      - name: Simulating an error
+        run: echo "error taking place" exit 1
       
     
