adding ; in the simulation error

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,6 +13,6 @@ jobs:
         run: echo "this workflow runs successfully for this particular action"
 
       - name: Simulating an error
-        run: echo "error taking place" exit 1
+        run: echo "error taking place"; exit 1
       
     
